### ISSUE TITLE
프로젝트 전개

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#1]
## Description
`yarn berry` + `react` + `vite` 프로젝트 전개

## TODO List
- [x] yarn berry 설정
- [x] react 19 + vite + yarn berry 프로젝트 전개

## Issue Check List
- [x] Title 규칙에 맞게 작성 ([domain] summary)
- [x] Labels 설정
- [x] Assignee 설정 (선택)
- [x] Due date 설정 (선택)
