### ISSUE TITLE
FSD 아키텍쳐 설계

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#2]
## Description
FSD 아키텍쳐 설계

## TODO List
- [ ] FSD 아키텍쳐 학습
- [ ] FSD 아키텍쳐 설계

## Issue Check List
- [x] Title 규칙에 맞게 작성 ([domain] summary)
- [x] Labels 설정
- [x] Assignee 설정 (선택)
- [x] Due date 설정 (선택)
