### ISSUE TITLE
Avatar Component 작업

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#20]
## Description
Avatar 컴포넌트 개발

## TODO List
- [ ] props 설정
- [ ] src, size, name, isDiabled, isBordered, radius, color, showFallback, fallback 등으로 Props 설계해 개발

## Check List
- [x] Labels 설정
- [ ] Assignee 설정 (선택)
- [ ] Due date 설정 (선택)
