### ISSUE TITLE
AvatarGroup Component 작업

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#21]
## Description
AvatarGroup 컴포넌트 작업

## TODO List
- [ ] AvatarGroup 컴포넌트 설계

## Check List
- [x] Labels 설정
- [ ] Assignee 설정 (선택)
- [ ] Due date 설정 (선택)
