### ISSUE TITLE
tailwind CSS config 작업

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#4]
## Description
작업할 내용에 대한 설명을 작성해주세요.

## TODO List
- [ ] tailwind CSS 설정 작업.
- [ ] 디자인 시스템 관련 스타일 추가

## Issue Check List
- [ ] Title 규칙에 맞게 작성 ([domain] summary)
- [ ] Labels 설정
- [ ] Assignee 설정 (선택)
- [ ] Due date 설정 (선택)
