### ISSUE TITLE
이슈, MR 템플릿 생성

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#5]
## Description
이슈, MR 템플릿 생성.

## TODO List
- [x] 이슈 템플릿 생성.
- [x] MR 템플릿 생성.

## Issue Check List
- [x] Title 규칙에 맞게 작성 ([domain] summary)
- [x] Labels 설정
- [x] Assignee 설정 (선택)
- [ ] Due date 설정 (선택)
