### ISSUE TITLE
esLint, Prettier 설정

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#6]
## Description
작업할 내용에 대한 설명을 작성해주세요.

## TODO List
- [x] esLint 설정
- [x] Prettier 설정

## Issue Check List
- [x] Title 규칙에 맞게 작성 ([domain] summary)
- [x] Labels 설정
- [x] Assignee 설정 (선택)
- [ ] Due date 설정 (선택)
