### ISSUE TITLE
필수 라이브러리 추가

### ISSUE THREAD

**Issue by bamin0422** [mission-ui/mission-ui#7]
## Description
필수 라이브러리 추가

## TODO List
- [x] framer-motion 추가
- [x] clsx 추가

## Issue Check List
- [x] Title 규칙에 맞게 작성 ([domain] summary)
- [x] Labels 설정
- [x] Assignee 설정 (선택)
- [x] Due date 설정 (선택)
